### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(KestrelContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

qt6_add_resources(${CMAKE_PROJECT_NAME} MainResource
    PREFIX "/qt/qml"
    VERSION 1.0
    FILES 
        "Kestrel/CMakeFiles/all_qmllint.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/all_qmllint_json.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/all_qmllint_module.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/all_qmltyperegistrations.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/clean_qml_context_properties.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/dump_qml_context_properties.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_autogen.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_autogen_timestamp_deps.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_copy_qml.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_copy_res.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_qmllint.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_qmllint_json.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_qmllint_module.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_qmltyperegistration.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_resources_1.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrel_resources_2.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrelplugin.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrelplugin_autogen.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrelplugin_autogen_timestamp_deps.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrelplugin_init.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrelplugin_init_autogen.dir/compiler_depend.ts"
        "Kestrel/CMakeFiles/Kestrelplugin_init_autogen_timestamp_deps.dir/compiler_depend.ts"
)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    KestrelContentplugin
    QtQuickDesignerComponents)