// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>


QT_DECLARE_EXTERN_RESOURCE(qmlcache_KestrelContent)
QT_DECLARE_EXTERN_RESOURCE(qmake_KestrelContent)
QT_DECLARE_EXTERN_RESOURCE(KestrelContent_raw_qml_0)
QT_DECLARE_EXTERN_RESOURCE(KestrelContent_raw_res_0)


QT_DECLARE_EXTERN_SYMBOL_VOID(qml_register_types_KestrelContent)

class KestrelContentPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    KestrelContentPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

QT_KEEP_SYMBOL(qml_register_types_KestrelContent)
QT_KEEP_RESOURCE(qmlcache_KestrelContent)
QT_KEEP_RESOURCE(qmake_KestrelContent)
QT_KEEP_RESOURCE(KestrelContent_raw_qml_0)
QT_KEEP_RESOURCE(KestrelContent_raw_res_0)
    }
};



#include "KestrelContentplugin_KestrelContentPlugin.moc"
